### ISSUE TITLE
Try this AppleALC with layout-id 49

### ISSUE THREAD

**Issue by VanXNF** [Old-Black-Dog/Hackintosh-ASRock-Z490M-ITX-ac#4]
Try this AppleALC with layout-id 49, I build a layout for this board. Remove FakePCIID, and it should work correctly.
Here is the file [AppleALC.kext](https://drive.google.com/drive/folders/1CgvFeT9IMn8lDBPVojaH_TKGB72svtQh?usp=sharing)

**Comment by risyomei** [comment]
@VanXNF 
Hey Van, I am quite interested in your file.
Can you share the process of building a board-specific layout?
I guess this repo can be used to track the change:
https://github.com/VanXNF/AppleALC

Is that correct?

**Comment by risyomei** [comment]
Okay, I can see that your contribution was merged: https://github.com/acidanthera/AppleALC/commit/8f9406ae6a93bc96400cda0096b78b7c1696dc9d

Thank you for that.
